### ISSUE TITLE
[Jaime]( Data-cleaning-Global-Shark-Attacks)

### ISSUE THREAD

**Issue by RCJaime** [Ironhack-Data-Madrid-Julio-2023/w2-project_pandas#10]
https://github.com/Jaimercmail/Data-cleaning-Global-Shark-Attacks

**Comment by OrianAmpuero** [comment]
Bien Jaime! Te dejo feedback del proyecto...

-Buen readme pero hubiese puesto menos gráficos (más resumido)
-Buena organización del repo
-Faltó limpieza
-Bien los gráficos pero a mi parecer muchos, eso era un plus

**Comment by RCJaime** [comment]
Bueno días Oriana!
Faltó limpieza en qué sentido?
Qué gráficos quitarías?

**Comment by OrianAmpuero** [comment]
Hola Jaime,
en el caso de limpieza siento que hubieses podido hacer otras cosas como la
columna edad pues rellenarla de otra forma para que fuese de tipo correcto
entero ya que tiene más sentido, o las columnas finales que quedaron NaN
las hubieses rellenado con la fecha que separaste para que se vea más
limpio el df. Luego, buena parte del jupyter es en base a los gráficos que
sacaste pero eso era un plus (bonus) este proyecto su principal objetivo
era limpieza y creo que le hubieses sacado más provecho a otros detalles de
las columnas que a los gráficos.

Es una opinión personal y obviamente es para que ustedes vayan tomando nota
y viendo que hacer y que no.

De resto muy bien!
