### ISSUE TITLE
[Esteban] (w2-project_pandas)

### ISSUE THREAD

**Issue by esteban-bit** [Ironhack-Data-Madrid-Julio-2023/w2-project_pandas#11]
Ver en rama master.  https://github.com/esteban-bit/data-cleaning-pandas.git

**Comment by OrianAmpuero** [comment]
Bien Esteban! Te dejo feedback del proyecto...

-Buen readme y organización del repo pero pendiente que tienes algunos archivos fuera de carpetas
-Muy bien comentado el código en jupyter
-Recuerda poner head para recortar el output
-Bien los gráficos para mejor visualización y resumen de los datos que hay
-cuidado con los tipos de dato
-no se guardo df final
