### ISSUE TITLE
borja.dolagaray_data-cleaning-pandas

### ISSUE THREAD

**Issue by borjadola** [Ironhack-Data-Madrid-Julio-2023/w2-project_pandas#12]
https://github.com/borjadola/Proyecto-Sharks_Attacks.git

**Comment by OrianAmpuero** [comment]
Muy buen trabajo Borja, ya lo comentamos antes, en general todo muy bien. Readme, carpetas en el repo, jupyter comentado y usando funciones, buena limpieza y análisis, además de gráficos para dar un plus....
Solo por apuntar algo, hubiese sido mejor que hicieras tu archivo .py para las funciones y las importaras en el jupyter notebook.
