### ISSUE TITLE
[David](data-cleaning-pandas)

### ISSUE THREAD

**Issue by DavidNPastrana** [Ironhack-Data-Madrid-Julio-2023/w2-project_pandas#13]
https://github.com/DavidNPastrana/Data-Cleaning-Project---Sharks

**Comment by OrianAmpuero** [comment]
Muy bien David! Te dejo unos comentarios que hablamos antes sobre el proyecto...
-readme mejorable
-organizar repo en carpetas
-time label lo pudiste usar en unnamed_1 o 2
-cuidar los tipos de datos (tomar decisiones en base al sentido que tiene la columna con el tipo de dato)
-bien la conclusión y gráficos finales como bonus
-no guardaste el df final ni un .info para ver como quedo el resultado
