### ISSUE TITLE
[Lola] (Sharks_project)

### ISSUE THREAD

**Issue by delbrioariasl** [Ironhack-Data-Madrid-Julio-2023/w2-project_pandas#14]
https://github.com/delbrioariasl/Sharks_project

**Comment by OrianAmpuero** [comment]
Bien Lola, ya lo hablamos pero te paso el feedback por aquí:
-Bien el readme pero falta organización de carpetas
-Cuidado con los tipos de datos
-Recuerda poner head() para recortar el output
