### ISSUE TITLE
[Rodrigo G.] (Shark Data Cleaning)

### ISSUE THREAD

**Issue by rodrigogtz99** [Ironhack-Data-Madrid-Julio-2023/w2-project_pandas#15]
https://github.com/rodrigogtz99/Proyecto-Pandas.git

**Comment by OrianAmpuero** [comment]
Bien Rodrigo! te dejo unos comenatrios del proyecto...
-README con mucho texto
-ordenar en carpetas
-archivo vacío ??
-te enfocaste mucho en las estaciones y lo demás?
-muy bien usado los gráficos
