### ISSUE TITLE
[DemianFigueiredo](PandasCleaning_Project_1)

### ISSUE THREAD

**Issue by DemianFigueiredo** [Ironhack-Data-Madrid-Julio-2023/w2-project_pandas#17]
https://github.com/DemianFigueiredo/shark_attack.git   That´s the same issue as i did wrongly in my own repository.

**Comment by OrianAmpuero** [comment]
Bien Demian!! Te envío el feedback para que lo tomes en cuenta:

-No hay readme
-falta organización de carpetas en el repo
-Recordar poner head() para que no sea tan largo el output
-Los tipos de datos de las columnas no tienen sentido (si es edad debería de ser número, es decir, int)
-No hay un .info al final del jupyter para ver como quedo el resumen de nulos y tipos de datos
-No se cargo o guardo el df (to_csv...)
