### ISSUE TITLE
[Nico GCD](W2 Project)

### ISSUE THREAD

**Issue by NGCOS46** [Ironhack-Data-Madrid-Julio-2023/w2-project_pandas#2]
https://github.com/NGCOS46/data-cleaning-pandas/tree/main

**Comment by OrianAmpuero** [comment]
Bien Nico, ya lo hablamos pero te paso por aquí el feedback:

-Readme mal, tienes el de Ironhack y debe ser propio
-Falta organización de carpetas en el repo
-Recuerda poner head() para recortar los outputs
-puedes hacer comentarios multilíneas con la triple comilla ''' ...... '''
