### ISSUE TITLE
[MartaRG] (w2-project_pandas)

### ISSUE THREAD

**Issue by MartaRggc** [Ironhack-Data-Madrid-Julio-2023/w2-project_pandas#3]
https://github.com/MartaRggc/Duck_to_shark

**Comment by OrianAmpuero** [comment]
Excelente trabajo Marta! Aquí va el feedback del que hablamos antes...
-Mejorar README
-Organizar repo por carpetas
-Muy bien comentado el código y lo que vas viendo de cada columna
-Excelente el hacer tu archivo .py
