### ISSUE TITLE
[IbaiGallego](SharkAttack)

### ISSUE THREAD

**Issue by IbaiGallego** [Ironhack-Data-Madrid-Julio-2023/w2-project_pandas#4]
https://github.com/IbaiGallego/DataCleaning_SharkAttack.git

**Comment by OrianAmpuero** [comment]
Buen trabajo Ibai! Te dejo unos comentarios a tomar en cuenta...
-Buen readme y repo organizado
-Bien comentado y organizado el código con la limpieza
-Cuidado con los tipos de dato
-Muy bien los gráficos para mostrar los datos y dar un plus (bonus)
