### ISSUE TITLE
[Margarita Hedo] Sharks Sharks Sharks

### ISSUE THREAD

**Issue by margahedo** [Ironhack-Data-Madrid-Julio-2023/w2-project_pandas#7]
https://github.com/margahedo/data-cleaning-pandas

**Comment by OrianAmpuero** [comment]
Muy bien Marga! Te dejo el feedback que comentamos antes...
-el readme está mal
-pocos commits para todo el finde
-recordar el HEAD (más de la mitad del jupyter es el df)
-los tipos de dato no los tocaste?
-TIME (remplazar la mayoría por unknown, haces perder info, es preferible dividir la info en mañana medio dia tarde y noche)
-cuando se repite mucho un código, es preferible crear función
-no terminas con un .info ni guardas el df final
