### ISSUE TITLE
[Nico.V](Sharks_data_cleansing)

### ISSUE THREAD

**Issue by nicovilla23** [Ironhack-Data-Madrid-Julio-2023/w2-project_pandas#8]
https://github.com/nicovilla23/Sharks_data_cleansing

**Comment by OrianAmpuero** [comment]
Muy bien Nico, te dejo unos comentarios del proyecto!

-Buen readme y organización del repo
-Poca limpieza 
-Cuidado con los tipos de datos
-Realizar un poco más de análisis para rellenar nulos
-Bien los gráficos para darle un plus (bonus)
