### ISSUE TITLE
[Carlos González](w2-project_pandas)

### ISSUE THREAD

**Issue by chiinwy** [Ironhack-Data-Madrid-Julio-2023/w2-project_pandas#9]
https://github.com/chiinwy/Proyecto_Tiburon

**Comment by OrianAmpuero** [comment]
Muy bien Carlos!! A pesar de haberlo hablado, te envío tu feedback por aquí:
-Mejorar el readme o hacerlo mejor dicho
-Crear carpetas
-Recuerda recortar los outputs porque si no es un dolor de cabeza revisar el jupyter notebook
-Bien usado los gráficos para dar una conclusión
